name: covid_choropleth
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py38h32f6830_1001
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.1=py_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38h32f6830_1001
  - importlib-metadata=1.5.0=py38h32f6830_1
  - importlib_metadata=1.5.0=1
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py38h5ca1d4c_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py38h32f6830_1
  - jinja2=2.11.1=py_0
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_client=6.0.0=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyterlab=2.0.1=py_0
  - jupyterlab_server=1.0.7=py_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libsodium=1.0.17=h01d97ff_0
  - markupsafe=1.1.1=py38h64e0658_1
  - mistune=0.8.4=py38h0b31af3_1000
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.0.15=py38h5e564d8_0
  - mkl_random=1.1.0=py38h6440ff4_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=h0a44026_0
  - notebook=6.0.3=py38_0
  - numpy=1.18.1=py38h7241aed_0
  - numpy-base=1.18.1=py38h6575580_1
  - openssl=1.1.1d=h1de35cc_4
  - pandas=1.0.1=py38h6c726b0_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.2=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38h32f6830_1001
  - pip=20.0.2=py38_1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyrsistent=0.15.7=py38h64e0658_1
  - python=3.8.1=h359304d_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py38h0a44026_0
  - readline=7.0=h1de35cc_5
  - send2trash=1.5.0=py_0
  - setuptools=46.0.0=py38_0
  - six=1.14.0=py_1
  - sqlite=3.31.1=ha441bb4_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py38h64e0658_1
  - traitlets=4.3.3=py38h32f6830_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/Colin/miniconda3/envs/covid_choropleth

